name: Packer

on:
  push:
    branches: [main]
  pull_request:
    # Run checks on reopened draft PRs to support triggering PR checks on draft PRs that were opened
    # by other workflows.
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/packer-github-actions@master
        with:
          command: fmt
          arguments: -check -diff
          target: .
